swagger: '2.0'
info:
  version: 0.0.6
  title: chance api
host: 'localhost:8081'
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /charges/build:
    x-swagger-router-controller: chargeController
    get:
      description: Builds sample charge file for import
      operationId: buildCharges
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/SuccessResponse'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorResponse'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/ErrorResponse'
        '403':
          description: Forbidden
          schema:
            $ref: '#/definitions/ErrorResponse'
        default:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
definitions:
  ErrorResponse:
    required:
      - code
      - message
    properties:
      code:
        type: integer
      message:
        type: string
  SuccessResponse:
    required:
      - message
    properties:
      message:
        type: string
